name: flutter_security_suite
description: "SecureBankKit - Enterprise-grade Flutter security plugin with root/jailbreak detection, certificate pinning, screenshot protection, app integrity checks, and secure storage."
version: 1.0.0
homepage: https://github.com/DeepakPal25/flutter_security_suite
repository: https://github.com/DeepakPal25/flutter_security_suite
issue_tracker: https://github.com/DeepakPal25/flutter_security_suite/issues
license: MIT

environment:
  sdk: ^3.10.4
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.securebankkit.flutter_security_suite
        pluginClass: SecureBankKitPlugin
      ios:
        pluginClass: SecureBankKitPlugin
